# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('active_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessid', models.CharField(max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=350)),
                ('url_title', models.CharField(max_length=200)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('salt', models.CharField(max_length=100)),
                ('hashpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sessions',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saver.User'),
        ),
        migrations.AddField(
            model_name='active',
            name='url_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saver.Url'),
        ),
        migrations.AddField(
            model_name='active',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saver.User'),
        ),
    ]
