# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
    ]
